version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: provider_api_app
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - redis
    networks:
      - provider_network
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - MAILER_DSN=${MAILER_DSN}

  nginx:
    image: nginx:alpine
    container_name: provider_api_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - provider_network

  db:
    image: mysql:5.7
    container_name: provider_api_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - provider_network

  redis:
    image: redis:latest
    container_name: provider_api_redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
    networks:
      - provider_network

  mailer:
    image: mailhog/mailhog
    container_name: provider_api_mailer
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - provider_network

networks:
  provider_network:
    driver: bridge
